- ---
- hosts: nexus_server
  become: yes
  tasks:

    - name: Update the system package index
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Install Java (OpenJDK 11)
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'RedHat'
        
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /tmp/nexus.tar.gz

    - name: Extract Nexus
      unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Rename the extracted directory
      command: mv /opt/nexus-3.72.0-04 /opt/nexus

    - name: Create Nexus user
      user:
        name: nexus
        home: /opt/nexus
        shell: /bin/bash

    - name: Change ownership of Nexus directories
      file:
        path: /opt/nexus
        owner: nexus
        group: nexus
        recurse: yes

    - name: Change ownership of Sonatype work directory
      command: chown -R nexus:nexus /opt/sonatype-work/nexus3

    - name: Set permissions for Sonatype work directory
      command: chmod -R 755 /opt/sonatype-work/nexus3

    - name: Configure Nexus to run as nexus user
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user='
        line: 'run_as_user="nexus"'

    - name: Set Nexus to run as a service
      copy:
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          ExecStart=/opt/nexus/bin/nexus start
          ExecStop=/opt/nexus/bin/nexus stop
          User=nexus
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/nexus.service

    - name: Reload systemd to apply new service
      systemd:
        daemon_reload: yes

    - name: Enable Nexus service
      systemd:
        name: nexus
        enabled: yes

    - name: Restart Nexus service
      systemd:
        name: nexus
        state: restarted

    - name: Ensure Nexus port (8081) is open in firewalld
      firewalld:
        service: nexus
        port: 8081/tcp
        permanent: yes
        state: enabled
        immediate: yes
        zone: public
      when: ansible_os_family == 'RedHat'
